CREATE TABLE kart (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(255) DEFAULT 'pending',
    coupon_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    total_price FLOAT
);

CREATE TABLE kart_ticket (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    kart_id BIGINT NOT NULL,
    ticket_id BIGINT NOT NULL,
    quantity INTEGER,
    FOREIGN KEY (kart_id) REFERENCES kart (id)
);